ARG BUILD_FROM
FROM safhdev/corosyncdevice:debianlatest

LABEL \
    io.hass.name="Corosync Device" \
    io.hass.description="Corosync QDevice for Proxmox 2-node Cluster" \
    io.hass.type="addon" \
    io.hass.version="dev" \
    io.hass.arch="${BUILD_ARCH}"
