ARG BUILD_FROM
FROM modelrockettier/corosync-qnetd:arm64v8

LABEL \
    io.hass.name="Corosync QNetd" \
    io.hass.description="Corosync Quorum Network Daemon for Proxmox Quorum" \
    io.hass.type="addon" \
    io.hass.version="dev" \
    io.hass.arch="${BUILD_ARCH}"
